### ISSUE TITLE
Mac requirements

### ISSUE THREAD

**Issue by arehmandev** [gambol99/kube-playground#1]
Heya just having a quick test of your repo, couple small things:

1) In run.kube the sed command for Mac must be as follows:
sed -i '' *restofcommand*
(the '' is necessary)

2) Default docker mac is /usr/local/bin, so must modify the default value of /usr/bin 
(I think just using 'docker' instead of /usr/bin/docker is the simplest solution)

3) aws_elb.kubeapi_internal: "name" cannot be longer than 32 characters: "play-absdevopscx-kube-internal-elb" 
(Cant have a long local username)

Other than that, all tested and working!

**Comment by gambol99** [comment]
Sorry for the delay .. Cheers for the heads up, i'll take a look at changing it now ..
